
os: osx

osx_image: xcode13.4

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

matrix:  # or you can replace `matrix` with `jobs`
  include:
    - name: "Python: 3.10"
      os: osx
      language: shell
      python: 3.10.4
      env: PYTHONVERSION=3.10.4
      cache:
        - directories:
          - $HOME/Library/Caches/pip

language: python

cache: pip

python:
  - "3.10"

before_install:
  - brew list
  - export PYTHON_CONFIGURE_OPTS="--enable-framework"
  - eval "$(pyenv init -)"
  - pyenv install $PYTHONVERSION
  - pyenv local $PYTHONVERSION
  - curl https://bootstrap.pypa.io/get-pip.py | python3

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
